Feat/add bottom navigation component
ourCat/ourCat_frontend pull request #42
Opened 2021-02-15 14:01 UTC by Denmark-Banana

Feat/add bottom navigation component

1. fontawesome pro가 아니라서 아이콘 on/off 용으로 사용 불가한 이슈
2. BottomNavigation 안에 있는 아이콘 박스를 molecules로 이동시켜야 하는지 논의

2021-02-16 12:37 UTC, spring1826 requested changes
수고하셨습니다. 수정해주세요

2021-02-16 12:37 UTC, spring1826 commented on src/components/organisms/BottomNavigation/style.ts
> +  justify-content: space-between;
justify-content: space-around를 적용하고 아래의 iconBox에는 flex를 빼주시면 좋을것같습니다.

2021-02-16 12:37 UTC, spring1826 commented on src/components/organisms/Header/style.ts
> +  background-color: ${props => props.theme.colors.GRAY[100]};
태그가 div면 더 적절할거같습니다.

2021-02-17 13:19 UTC, Denmark-Banana commented on src/components/organisms/BottomNavigation/style.ts
> +  justify-content: space-between;
네 수정했습니다.

2021-02-17 13:21 UTC, Denmark-Banana commented on src/components/organisms/Header/style.ts
> +  background-color: ${props => props.theme.colors.GRAY[100]};
네 수정했습니다.

2021-02-17 14:36 UTC, merged